[tool.poetry]
name = "flet-todo"
version = "0.1.0"
description = ""
authors = ["daichi2mori"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flet = "^0.21.2"
black = "^24.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
